/* Automatically generated by tree-sitter v0.25.3 (2a835ee029dca1c325e6f1c01dbce40396f6123e) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 29
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 30
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 3
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 9
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment = 1,
  anon_sym_export = 2,
  anon_sym_local = 3,
  anon_sym_COMMA = 4,
  anon_sym_EQ = 5,
  anon_sym_PLUS_EQ = 6,
  anon_sym_DASH_EQ = 7,
  anon_sym_SLASH_EQ = 8,
  anon_sym_STAR_EQ = 9,
  anon_sym_PERCENT_EQ = 10,
  anon_sym_DOT_DOT_EQ = 11,
  anon_sym_and_EQ = 12,
  anon_sym_or_EQ = 13,
  sym_identifier = 14,
  sym_number = 15,
  sym_string = 16,
  anon_sym_true = 17,
  anon_sym_false = 18,
  sym_indent = 19,
  sym_dedent = 20,
  sym_error_sentinel = 21,
  sym_source_file = 22,
  sym__expression = 23,
  sym_assignment = 24,
  sym__assignment_op = 25,
  sym_boolean = 26,
  aux_sym_source_file_repeat1 = 27,
  aux_sym_assignment_repeat1 = 28,
  aux_sym_assignment_repeat2 = 29,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [anon_sym_export] = "export",
  [anon_sym_local] = "local",
  [anon_sym_COMMA] = ",",
  [anon_sym_EQ] = "=",
  [anon_sym_PLUS_EQ] = "+=",
  [anon_sym_DASH_EQ] = "-=",
  [anon_sym_SLASH_EQ] = "/=",
  [anon_sym_STAR_EQ] = "*=",
  [anon_sym_PERCENT_EQ] = "%=",
  [anon_sym_DOT_DOT_EQ] = "..=",
  [anon_sym_and_EQ] = "and=",
  [anon_sym_or_EQ] = "or=",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [sym_string] = "string",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_indent] = "indent",
  [sym_dedent] = "dedent",
  [sym_error_sentinel] = "error_sentinel",
  [sym_source_file] = "source_file",
  [sym__expression] = "_expression",
  [sym_assignment] = "assignment",
  [sym__assignment_op] = "_assignment_op",
  [sym_boolean] = "boolean",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_assignment_repeat1] = "assignment_repeat1",
  [aux_sym_assignment_repeat2] = "assignment_repeat2",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [anon_sym_export] = anon_sym_export,
  [anon_sym_local] = anon_sym_local,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_PLUS_EQ] = anon_sym_PLUS_EQ,
  [anon_sym_DASH_EQ] = anon_sym_DASH_EQ,
  [anon_sym_SLASH_EQ] = anon_sym_SLASH_EQ,
  [anon_sym_STAR_EQ] = anon_sym_STAR_EQ,
  [anon_sym_PERCENT_EQ] = anon_sym_PERCENT_EQ,
  [anon_sym_DOT_DOT_EQ] = anon_sym_DOT_DOT_EQ,
  [anon_sym_and_EQ] = anon_sym_and_EQ,
  [anon_sym_or_EQ] = anon_sym_or_EQ,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_indent] = sym_indent,
  [sym_dedent] = sym_dedent,
  [sym_error_sentinel] = sym_error_sentinel,
  [sym_source_file] = sym_source_file,
  [sym__expression] = sym__expression,
  [sym_assignment] = sym_assignment,
  [sym__assignment_op] = sym__assignment_op,
  [sym_boolean] = sym_boolean,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_assignment_repeat1] = aux_sym_assignment_repeat1,
  [aux_sym_assignment_repeat2] = aux_sym_assignment_repeat2,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_export] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_local] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_or_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_indent] = {
    .visible = true,
    .named = true,
  },
  [sym_dedent] = {
    .visible = true,
    .named = true,
  },
  [sym_error_sentinel] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym__assignment_op] = {
    .visible = false,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_assignment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_assignment_repeat2] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_destination = 1,
  field_source = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_destination] = "destination",
  [field_source] = "source",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 4, .length = 3},
  [4] = {.index = 7, .length = 3},
  [5] = {.index = 10, .length = 3},
  [6] = {.index = 13, .length = 3},
  [7] = {.index = 16, .length = 4},
  [8] = {.index = 20, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_destination, 0},
    {field_source, 2},
  [2] =
    {field_destination, 1},
    {field_source, 3},
  [4] =
    {field_destination, 0},
    {field_source, 2},
    {field_source, 3},
  [7] =
    {field_destination, 0},
    {field_destination, 1},
    {field_source, 3},
  [10] =
    {field_destination, 1},
    {field_source, 3},
    {field_source, 4},
  [13] =
    {field_destination, 1},
    {field_destination, 2},
    {field_source, 4},
  [16] =
    {field_destination, 0},
    {field_destination, 1},
    {field_source, 3},
    {field_source, 4},
  [20] =
    {field_destination, 1},
    {field_destination, 2},
    {field_source, 4},
    {field_source, 5},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(19);
      ADVANCE_MAP(
        '"', 2,
        '%', 8,
        '*', 9,
        '+', 10,
        ',', 23,
        '-', 5,
        '.', 7,
        '/', 11,
        '=', 24,
        'e', 48,
        'f', 33,
        'l', 40,
        't', 43,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == 'f') ADVANCE(33);
      if (lookahead == 't') ADVANCE(43);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '%', 8,
        '*', 9,
        '+', 10,
        ',', 23,
        '-', 5,
        '.', 7,
        '/', 11,
        '=', 24,
        'a', 16,
        'o', 17,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(20);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(20);
      if (lookahead == '=') ADVANCE(26);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 7:
      if (lookahead == '.') ADVANCE(12);
      END_STATE();
    case 8:
      if (lookahead == '=') ADVANCE(29);
      END_STATE();
    case 9:
      if (lookahead == '=') ADVANCE(28);
      END_STATE();
    case 10:
      if (lookahead == '=') ADVANCE(25);
      END_STATE();
    case 11:
      if (lookahead == '=') ADVANCE(27);
      END_STATE();
    case 12:
      if (lookahead == '=') ADVANCE(30);
      END_STATE();
    case 13:
      if (lookahead == '=') ADVANCE(32);
      END_STATE();
    case 14:
      if (lookahead == '=') ADVANCE(31);
      END_STATE();
    case 15:
      if (lookahead == 'd') ADVANCE(14);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(15);
      END_STATE();
    case 17:
      if (lookahead == 'r') ADVANCE(13);
      END_STATE();
    case 18:
      if (eof) ADVANCE(19);
      if (lookahead == ',') ADVANCE(23);
      if (lookahead == '-') ADVANCE(4);
      if (lookahead == 'e') ADVANCE(48);
      if (lookahead == 'l') ADVANCE(40);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(18);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_export);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_local);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_PLUS_EQ);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_DASH_EQ);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_SLASH_EQ);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_STAR_EQ);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_PERCENT_EQ);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_DOT_DOT_EQ);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_and_EQ);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_or_EQ);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(38);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(39);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(34);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(53);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(45);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(22);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(35);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(44);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(41);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(47);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(46);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(21);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'x') ADVANCE(42);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '"') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_true);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_false);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 18},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 3},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 18},
  [14] = {.lex_state = 18},
  [15] = {.lex_state = 18},
  [16] = {.lex_state = 18},
  [17] = {.lex_state = 18},
  [18] = {.lex_state = 18},
  [19] = {.lex_state = 18},
  [20] = {.lex_state = 18},
  [21] = {.lex_state = 18},
  [22] = {.lex_state = 18},
  [23] = {.lex_state = 18},
  [24] = {.lex_state = 18},
  [25] = {.lex_state = 18},
  [26] = {.lex_state = 6},
  [27] = {.lex_state = 6},
  [28] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_export] = ACTIONS(1),
    [anon_sym_local] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_PLUS_EQ] = ACTIONS(1),
    [anon_sym_DASH_EQ] = ACTIONS(1),
    [anon_sym_SLASH_EQ] = ACTIONS(1),
    [anon_sym_STAR_EQ] = ACTIONS(1),
    [anon_sym_PERCENT_EQ] = ACTIONS(1),
    [anon_sym_DOT_DOT_EQ] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_indent] = ACTIONS(1),
    [sym_dedent] = ACTIONS(1),
    [sym_error_sentinel] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(28),
    [sym_assignment] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
    [anon_sym_export] = ACTIONS(7),
    [anon_sym_local] = ACTIONS(7),
    [sym_identifier] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_COMMA,
    STATE(6), 1,
      aux_sym_assignment_repeat1,
    STATE(12), 1,
      sym__assignment_op,
    ACTIONS(13), 9,
      anon_sym_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_SLASH_EQ,
      anon_sym_STAR_EQ,
      anon_sym_PERCENT_EQ,
      anon_sym_DOT_DOT_EQ,
      anon_sym_and_EQ,
      anon_sym_or_EQ,
  [24] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_COMMA,
    STATE(2), 1,
      aux_sym_assignment_repeat1,
    STATE(8), 1,
      sym__assignment_op,
    ACTIONS(15), 9,
      anon_sym_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_SLASH_EQ,
      anon_sym_STAR_EQ,
      anon_sym_PERCENT_EQ,
      anon_sym_DOT_DOT_EQ,
      anon_sym_and_EQ,
      anon_sym_or_EQ,
  [48] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_COMMA,
    STATE(5), 1,
      aux_sym_assignment_repeat1,
    STATE(9), 1,
      sym__assignment_op,
    ACTIONS(17), 9,
      anon_sym_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_SLASH_EQ,
      anon_sym_STAR_EQ,
      anon_sym_PERCENT_EQ,
      anon_sym_DOT_DOT_EQ,
      anon_sym_and_EQ,
      anon_sym_or_EQ,
  [72] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_COMMA,
    STATE(6), 1,
      aux_sym_assignment_repeat1,
    STATE(10), 1,
      sym__assignment_op,
    ACTIONS(19), 9,
      anon_sym_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_SLASH_EQ,
      anon_sym_STAR_EQ,
      anon_sym_PERCENT_EQ,
      anon_sym_DOT_DOT_EQ,
      anon_sym_and_EQ,
      anon_sym_or_EQ,
  [96] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_COMMA,
    STATE(6), 1,
      aux_sym_assignment_repeat1,
    ACTIONS(24), 9,
      anon_sym_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_SLASH_EQ,
      anon_sym_STAR_EQ,
      anon_sym_PERCENT_EQ,
      anon_sym_DOT_DOT_EQ,
      anon_sym_and_EQ,
      anon_sym_or_EQ,
  [117] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(24), 10,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_PLUS_EQ,
      anon_sym_DASH_EQ,
      anon_sym_SLASH_EQ,
      anon_sym_STAR_EQ,
      anon_sym_PERCENT_EQ,
      anon_sym_DOT_DOT_EQ,
      anon_sym_and_EQ,
      anon_sym_or_EQ,
  [133] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(26), 1,
      sym_identifier,
    ACTIONS(28), 2,
      sym_number,
      sym_string,
    ACTIONS(30), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(17), 2,
      sym__expression,
      sym_boolean,
  [152] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(32), 1,
      sym_identifier,
    ACTIONS(30), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(34), 2,
      sym_number,
      sym_string,
    STATE(15), 2,
      sym__expression,
      sym_boolean,
  [171] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(36), 1,
      sym_identifier,
    ACTIONS(30), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(38), 2,
      sym_number,
      sym_string,
    STATE(21), 2,
      sym__expression,
      sym_boolean,
  [190] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(40), 1,
      sym_identifier,
    ACTIONS(30), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(42), 2,
      sym_number,
      sym_string,
    STATE(24), 2,
      sym__expression,
      sym_boolean,
  [209] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(44), 1,
      sym_identifier,
    ACTIONS(30), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(46), 2,
      sym_number,
      sym_string,
    STATE(19), 2,
      sym__expression,
      sym_boolean,
  [228] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(48), 1,
      ts_builtin_sym_end,
    ACTIONS(7), 2,
      anon_sym_export,
      anon_sym_local,
    STATE(14), 2,
      sym_assignment,
      aux_sym_source_file_repeat1,
  [246] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 1,
      ts_builtin_sym_end,
    ACTIONS(55), 1,
      sym_identifier,
    ACTIONS(52), 2,
      anon_sym_export,
      anon_sym_local,
    STATE(14), 2,
      sym_assignment,
      aux_sym_source_file_repeat1,
  [264] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 1,
      ts_builtin_sym_end,
    ACTIONS(62), 1,
      anon_sym_COMMA,
    STATE(20), 1,
      aux_sym_assignment_repeat2,
    ACTIONS(60), 3,
      anon_sym_export,
      anon_sym_local,
      sym_identifier,
  [282] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 1,
      ts_builtin_sym_end,
    ACTIONS(68), 1,
      anon_sym_COMMA,
    STATE(16), 1,
      aux_sym_assignment_repeat2,
    ACTIONS(66), 3,
      anon_sym_export,
      anon_sym_local,
      sym_identifier,
  [300] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 1,
      anon_sym_COMMA,
    ACTIONS(71), 1,
      ts_builtin_sym_end,
    STATE(18), 1,
      aux_sym_assignment_repeat2,
    ACTIONS(73), 3,
      anon_sym_export,
      anon_sym_local,
      sym_identifier,
  [318] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 1,
      anon_sym_COMMA,
    ACTIONS(75), 1,
      ts_builtin_sym_end,
    STATE(16), 1,
      aux_sym_assignment_repeat2,
    ACTIONS(77), 3,
      anon_sym_export,
      anon_sym_local,
      sym_identifier,
  [336] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 1,
      anon_sym_COMMA,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
    STATE(22), 1,
      aux_sym_assignment_repeat2,
    ACTIONS(81), 3,
      anon_sym_export,
      anon_sym_local,
      sym_identifier,
  [354] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 1,
      anon_sym_COMMA,
    ACTIONS(83), 1,
      ts_builtin_sym_end,
    STATE(16), 1,
      aux_sym_assignment_repeat2,
    ACTIONS(85), 3,
      anon_sym_export,
      anon_sym_local,
      sym_identifier,
  [372] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 1,
      anon_sym_COMMA,
    ACTIONS(87), 1,
      ts_builtin_sym_end,
    STATE(23), 1,
      aux_sym_assignment_repeat2,
    ACTIONS(89), 3,
      anon_sym_export,
      anon_sym_local,
      sym_identifier,
  [390] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 1,
      anon_sym_COMMA,
    ACTIONS(91), 1,
      ts_builtin_sym_end,
    STATE(16), 1,
      aux_sym_assignment_repeat2,
    ACTIONS(93), 3,
      anon_sym_export,
      anon_sym_local,
      sym_identifier,
  [408] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 1,
      anon_sym_COMMA,
    ACTIONS(95), 1,
      ts_builtin_sym_end,
    STATE(16), 1,
      aux_sym_assignment_repeat2,
    ACTIONS(97), 3,
      anon_sym_export,
      anon_sym_local,
      sym_identifier,
  [426] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 2,
      ts_builtin_sym_end,
      anon_sym_COMMA,
    ACTIONS(66), 3,
      anon_sym_export,
      anon_sym_local,
      sym_identifier,
  [439] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 2,
      ts_builtin_sym_end,
      anon_sym_COMMA,
    ACTIONS(101), 3,
      anon_sym_export,
      anon_sym_local,
      sym_identifier,
  [452] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 1,
      sym_identifier,
  [459] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 1,
      sym_identifier,
  [466] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 24,
  [SMALL_STATE(4)] = 48,
  [SMALL_STATE(5)] = 72,
  [SMALL_STATE(6)] = 96,
  [SMALL_STATE(7)] = 117,
  [SMALL_STATE(8)] = 133,
  [SMALL_STATE(9)] = 152,
  [SMALL_STATE(10)] = 171,
  [SMALL_STATE(11)] = 190,
  [SMALL_STATE(12)] = 209,
  [SMALL_STATE(13)] = 228,
  [SMALL_STATE(14)] = 246,
  [SMALL_STATE(15)] = 264,
  [SMALL_STATE(16)] = 282,
  [SMALL_STATE(17)] = 300,
  [SMALL_STATE(18)] = 318,
  [SMALL_STATE(19)] = 336,
  [SMALL_STATE(20)] = 354,
  [SMALL_STATE(21)] = 372,
  [SMALL_STATE(22)] = 390,
  [SMALL_STATE(23)] = 408,
  [SMALL_STATE(24)] = 426,
  [SMALL_STATE(25)] = 439,
  [SMALL_STATE(26)] = 452,
  [SMALL_STATE(27)] = 459,
  [SMALL_STATE(28)] = 466,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_assignment_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [24] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_assignment_repeat1, 2, 0, 0),
  [26] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [30] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [32] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [36] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [40] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 4, 0, 2),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 4, 0, 2),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_assignment_repeat2, 2, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_assignment_repeat2, 2, 0, 0),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_assignment_repeat2, 2, 0, 0), SHIFT_REPEAT(11),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3, 0, 1),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 3, 0, 1),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 4, 0, 3),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 4, 0, 3),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 4, 0, 4),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 4, 0, 4),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 5, 0, 5),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 5, 0, 5),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 5, 0, 6),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 5, 0, 6),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 5, 0, 7),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 5, 0, 7),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 6, 0, 8),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 6, 0, 8),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [107] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_indent = 0,
  ts_external_token_dedent = 1,
  ts_external_token_error_sentinel = 2,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_indent] = sym_indent,
  [ts_external_token_dedent] = sym_dedent,
  [ts_external_token_error_sentinel] = sym_error_sentinel,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_indent] = true,
    [ts_external_token_dedent] = true,
    [ts_external_token_error_sentinel] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_moonscript_external_scanner_create(void);
void tree_sitter_moonscript_external_scanner_destroy(void *);
bool tree_sitter_moonscript_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_moonscript_external_scanner_serialize(void *, char *);
void tree_sitter_moonscript_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_moonscript(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_moonscript_external_scanner_create,
      tree_sitter_moonscript_external_scanner_destroy,
      tree_sitter_moonscript_external_scanner_scan,
      tree_sitter_moonscript_external_scanner_serialize,
      tree_sitter_moonscript_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "moonscript",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
